Randcast Solidity Contracts: Initial Commit
ARPA-Network/BLS-TSS-Network pull request #10
Opened 2022-11-08 03:10 UTC by wrinkledeth

This is the current state of Randcast contract development:
- Coordinator contract complete
- Controller in progress (node register + commit dkg + post process dkg)

Seeking code review to make sure things are progressing on the correct path.

2022-11-15 10:20 UTC, kafeikui commented on contracts/notes.md
> +is there a reason why you check for length !=0 instead of just partial key !=0.
Because partialPublicKey has a type of bytes which can't be compared directly with int.

2022-11-15 10:24 UTC, kafeikui commented on contracts/src/Controller.sol
> +                return isExist;
We can make it as "return true" and delete line 334.

2022-11-15 10:28 UTC, kafeikui commented on contracts/src/Coordinator.sol
> +        require(participant_map[msg.sender], "you are not registered!");
We can judge if msg.sender is qualified to publish by iterating the participants. Let's remove participant_map to save gas for storage.

2022-11-15 10:30 UTC, kafeikui commented on contracts/src/Coordinator.sol
> +            participant_map[nodes[i]] = true;
Let's remove this.

2022-11-15 10:33 UTC, kafeikui commented on contracts/src/Coordinator.sol
> +    function getBlsKeys() external view returns (uint256, bytes[] memory) {
It shoud be DkgKeys for encrypted communication.

2022-11-15 10:38 UTC, kafeikui commented on contracts/src/ICoordinator.sol
> +    event OwnershipTransferred(
I don't think this should be included as functions of ICoordinator, as we can still call them by Ownable if needed.

2022-11-15 10:38 UTC, kafeikui commented on contracts/src/ICoordinator.sol
> +    function renounceOwnership() external;
The same above.

2022-11-15 10:39 UTC, kafeikui commented on contracts/src/ICoordinator.sol
> +    function owner() external view returns (address);
The same above.

2022-11-15 10:39 UTC, kafeikui commented on contracts/src/ICoordinator.sol
> +    function transferOwnership(address newOwner) external;
The same above.

2022-11-15 10:43 UTC, kafeikui commented on contracts/src/Controller.sol
> +    mapping(address => bool) public nodeRegistered; // map for checking if nodes are registered
I think we already have a nodes mapping which should be enough for locating and checking a node's state.

2022-11-15 10:45 UTC, kafeikui commented on contracts/src/Controller.sol
> +    mapping(uint256 => bool) public groupRegistered; // map for checking if group exists
The same above. Storage accounts for almost the largest proportion of gas cost.

2022-11-15 10:48 UTC, kafeikui commented on contracts/src/Controller.sol
> +    mapping(address => uint256) public rewards; // maps node address to reward amount
Actually it's not for nodes only or we can merge it to node struct. Well let's hold it for now.

2022-11-15 10:50 UTC, kafeikui commented on contracts/src/Controller.sol
> +        uint256 pending_until_block;
NIT: camel case in solidity.

2022-11-15 10:53 UTC, kafeikui commented on contracts/src/Controller.sol
> +        rewards[msg.sender] = 0; // This can be removed
I agree.

2022-11-15 11:01 UTC, kafeikui commented on contracts/src/Controller.sol
> +
Here we need to reset is_strictly_majority_consensus_reached of the current group to false.

2022-11-15 11:04 UTC, kafeikui commented on contracts/src/Controller.sol
> +
It's better to reset commit_cache and committers to empty.

2022-11-15 11:12 UTC, kafeikui commented on contracts/src/Controller.sol
> +
Remind: Don't forget to check the format of publicKey and partialPublicKey here.

2022-11-15 11:13 UTC, kafeikui commented on contracts/src/Controller.sol
> +    function commitDkg(
Later we can refactor this input params to a struct to save local variables usage.

2022-11-15 11:28 UTC, kafeikui requested changes
Thanks for the endeavor! There may be some changes before starting review so that they are not labeled as pending. Please check them and let me know if there's any problem.

2022-11-15 11:28 UTC, kafeikui commented on contracts/src/Controller.sol
> +        require(phase != -1, "DKG Has ended"); // require coordinator is in phase 1
phase == -1, nodes can't call postProcess until the DKG phase is ended.

2022-11-15 11:28 UTC, kafeikui commented on contracts/src/Controller.sol
> +        // Coordinator Self Destruct
Yeah so we need to add ownable Self Destruct function to coordinator.

2022-11-18 00:01 UTC, wrinkledeth commented on contracts/notes.md
> +is there a reason why you check for length !=0 instead of just partial key !=0.
understood!

2022-11-18 00:03 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                return isExist;
done.

2022-11-18 00:06 UTC, wrinkledeth commented on contracts/src/ICoordinator.sol
> +    event OwnershipTransferred(
removed.

2022-11-18 00:07 UTC, wrinkledeth commented on contracts/src/ICoordinator.sol
> +    function transferOwnership(address newOwner) external;
removed

2022-11-18 00:07 UTC, wrinkledeth commented on contracts/src/ICoordinator.sol
> +    function owner() external view returns (address);
removed

2022-11-18 00:07 UTC, wrinkledeth commented on contracts/src/ICoordinator.sol
> +    function renounceOwnership() external;
removed

2022-11-18 00:10 UTC, wrinkledeth commented on contracts/src/Coordinator.sol
> +    function getBlsKeys() external view returns (uint256, bytes[] memory) {
done. Also refactored ICoordinator.sol and Coordinator.t.sol

2022-11-18 00:12 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        uint256 pending_until_block;
done

2022-11-18 00:13 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        rewards[msg.sender] = 0; // This can be removed
removed

2022-11-18 00:15 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        uint256 min = groupSize / 2 + 1;
done

2022-11-18 00:27 UTC, wrinkledeth commented on contracts/src/Coordinator.sol
> +        require(participant_map[msg.sender], "you are not registered!");
Fixed. Added iteration logic within "modifier onlyRegistered()"

2022-11-18 00:27 UTC, wrinkledeth commented on contracts/src/Coordinator.sol
> +            participant_map[nodes[i]] = true;
removed

2022-11-18 01:03 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +    mapping(address => bool) public nodeRegistered; // map for checking if nodes are registered
resolved! 

```js
       require(
            nodes[msg.sender].idAddress == address(0),
            "Node is already registered"
        ); // error sender already in list of node
```

2022-11-18 01:04 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +    mapping(uint256 => bool) public groupRegistered; // map for checking if group exists
resolved! 

```js
        require(groups[groupIndex].index != 0, "Group does not exist");

```

2022-11-18 01:44 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +
Can you check if this is an okay way to do it? 

```js
```

2022-11-22 04:09 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        // Coordinator Self Destruct
completed, however it is currently not possible to test selfDestruct using Foundry / Forge: (https://github.com/foundry-rs/foundry/issues/1543). Need to research other options or wait for this feature to be added (https://github.com/foundry-rs/foundry/issues/2844)

2022-11-22 14:58 UTC, kafeikui commented on contracts/test/Controller.t.sol
> +        testCommitDkg();
I think it's better to setup the context directly rather than execute `testCommitDkg()` again.

2022-11-22 17:49 UTC, wrinkledeth commented on contracts/test/Controller.t.sol
> +        testCommitDkg();
fixed

2022-11-23 16:36 UTC, kafeikui requested changes

2022-11-24 17:23 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        require(coordinator.inPhase() == -1, "DKG still in progress"); // require DKG Phase End.
fixed

2022-11-24 17:24 UTC, wrinkledeth commented on contracts/src/ICoordinator.sol
> -    function keys(address) external view returns (bytes memory);
fixed, test for phase = -1 has been move to the end of testCommitDkg():
```js
```

2022-11-24 17:25 UTC, wrinkledeth commented on contracts/test/Controller.t.sol
> +        vm.roll(startBlock + 1 + 4 * PHASE_DURATION); // Put the coordinator in phase
fixed, test for phase = -1 has been move to the end of testCommitDkg()

2022-11-24 17:29 UTC, wrinkledeth commented on contracts/src/ICoordinator.sol
> -    function keys(address) external view returns (bytes memory);
Fixed. I believe we need `selfDestruct` as well.

2022-11-24 17:36 UTC, wrinkledeth commented on contracts/src/Coordinator.sol
>      modifier onlyRegistered() {
completed

2022-11-24 17:38 UTC, wrinkledeth commented on contracts/src/Coordinator.sol
>      /// Gets the participants' BLS keys along with the thershold of the DKG
fixed. Thank you for the insight about the DKG key format.

2022-11-25 07:16 UTC, kafeikui commented on contracts/src/Controller.sol
> +        require(coordinator.inPhase() != -1, "DKG has ended"); // require coordinatos to still be in DKG Phase
typo, "coordinator"

2022-11-25 07:41 UTC, kafeikui commented on contracts/src/Coordinator.sol
>      modifier onlyGroupMember() {
Inspired by the comment, I think we can check by 
`require(keys[msg.sender].length > 0, "you are not a group member!");`
 to further save gas.

2022-11-25 07:43 UTC, kafeikui approved these changes
LGTM, please check the latest comments then merge the branch.

2022-11-27 20:42 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        require(coordinator.inPhase() != -1, "DKG has ended"); // require coordinatos to still be in DKG Phase
fixed

2022-11-27 20:48 UTC, wrinkledeth commented on contracts/src/Coordinator.sol
>      modifier onlyGroupMember() {
Wow this is great. Nice catch!

2022-11-27 21:26 UTC, merged