Complete commitdkg
ARPA-Network/BLS-TSS-Network pull request #13
Opened 2022-12-27 02:09 UTC by wrinkledeth

commitDKG() (and related functions such as slashNode()) have been fully implemented. 

Notable Changes:
- Refactored the input parameters into a struct to solve "stack to deep" errors. 
- Refactored Member Struct: removed member.index . Using position in members array instead.
- Fixed bug in partialKeyRegistered() and getMemberIndex()
- emitGroupEvent() now actually emitting an event.

I also went back and finished implementing remaining nodeRegister() functions:
- reblanceGroup()
- chooseRandomlyFromIndices()
- removeFromGroup()
- findOrCreateTargetGroup()

Remaining: 
- freezeNode()
- postProccessDkg()

2022-12-27 10:56 UTC, kafeikui requested changes
Review on `commitDkg`. Nice implementation of `chooseRandomlyFromIndices`!

2022-12-27 10:56 UTC, kafeikui commented on contracts/src/Controller.sol
> +                // Get list of majority members with disqualified nodes excluded
thumb-up

2022-12-27 10:56 UTC, kafeikui commented on contracts/src/Controller.sol
> +                    }
Here we can move iteration of majorityMembers into outer and break after inner if condition passes to save gas.

2022-12-27 10:56 UTC, kafeikui commented on contracts/src/Controller.sol
>      }
nice

2022-12-27 10:56 UTC, kafeikui commented on contracts/src/Controller.sol
> +                    }
Wait, here with this deleting style the resolved committer indices will get effected. Let's move forward the logic of removing all disqualified members to line 519.

2022-12-27 10:56 UTC, kafeikui commented on contracts/src/Controller.sol
> +                            }
Let's add a break here.

2022-12-27 11:28 UTC, kafeikui commented on contracts/src/Controller.sol
> +        for (uint256 i = 0; i < groupCount; i++) {
Here I think it's better to count from i = 1.

2022-12-27 11:39 UTC, kafeikui commented on contracts/src/Controller.sol
> +        require(groupIndex != 0, "Group index cannot be 0"); // remove?
I agree. And somehow I wonder the reason of the requirement here.

2022-12-27 11:41 UTC, kafeikui commented on contracts/src/Controller.sol
> +        }
It's getting weird. Let's count group from index 0 instead of index 1.

2022-12-27 11:45 UTC, kafeikui commented on contracts/src/Controller.sol
> +        // If needs rebalance, iterate over group indices and attempt to rebalance group, break as soon as success
Exactly! I should have used for-loop in rust code. That's more straightforward.

2022-12-27 11:57 UTC, kafeikui commented on contracts/src/Controller.sol
> +            for (uint256 j = 0; j < groupA.members.length; j++) {
I think we can extract some internal function like `getMemberAddressByIndex` `getMemberIndexByAddress` and reuse them.

2022-12-27 12:55 UTC, kafeikui commented on contracts/src/Controller.sol
> +            (validGroupCount == groupCount)
It's not about your code here, but I believe I made a mistake in design that if the existing groups are full of members but not all of them are valid(not finishing DKG), then new-comer node will enter the first group and make size of the group exceed `GROUP_MAX_CAPACITY`.

I think the condition should be `(valid_group_count < IDEAL_NUMBER_OF_GROUPS && valid_group_count == self.groups.len())
            || min_size == GROUP_MAX_CAPACITY`. I'd like to know your opinions.

2023-01-14 23:50 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +            (validGroupCount == groupCount)
I agree with the above. Completed

2023-01-14 23:50 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        require(groupIndex != 0, "Group index cannot be 0"); // remove?
removed

2023-01-14 23:54 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                            }
break added

2023-01-14 23:59 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                    }
done. Moved the for loop further up.

2023-01-15 00:05 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                    }
completed

2023-01-19 12:00 UTC, kafeikui commented on contracts/src/Controller.sol
> +        uint256[] memory remainingIndices = indices;
Hey I just found that this function is not absolutely "pure" for `indices`. When you modify `remainingIndices`, `indices` will aslo get affected. Although in our cases, there is no reference to the `indices` in the following code after calling the current function, I would suggest maintaining a `remainingIndices` as [0, 1, ..., indices.length-1] inside `chooseRandomlyFromIndices` to avoid actually modifying `indices`.

2023-01-26 21:15 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        }
completed this refactor

2023-01-26 21:16 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        for (uint256 i = 0; i < groupCount; i++) {
completed this refactor (groupIndex starts from 1)

2023-01-26 21:17 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        for (uint256 i = 0; i < g.commitCacheList.length; i++) {
completed

2023-01-26 21:24 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        uint256[] memory remainingIndices = indices;
I am not 100% clear on the ask here. Since remaining indices is declared as memory, doesn't it mean that indices will not be modified?

2023-01-26 21:29 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +            for (uint256 j = 0; j < groupA.members.length; j++) {
Done. We have two functions now: getMemberIndexByAddress and getMemberAddressByIndex

2023-01-27 02:44 UTC, kafeikui commented on contracts/src/Controller.sol
> +        uint256[] memory remainingIndices = indices;
Array in solidity is mutable by reference, just like in other languages like python. If we modify `indices` to another array value, it will have no effect after return. However if we modify the `indices` by index, then array value will get modified after return. 

Pure in solidity only guarantees states(storage variables) will not get changed. I suggest modifying the codes in the `chooseRandomlyFromIndices` so that `indices` will not be modified, as "pure" literally for our cases, even though "pure" is not designed for that in solidity.

2023-01-27 02:58 UTC, kafeikui commented on contracts/src/Controller.sol
>          }
Let's move the codes of building `groupIndices` to if clause below.

2023-01-27 03:16 UTC, kafeikui commented on contracts/src/Controller.sol
> +        CommitCache memory majorityCommitCache = g.commitCacheList[1];
It should be the first element of `g.commitCacheList`

2023-01-27 03:26 UTC, kafeikui commented on contracts/src/Controller.sol
> +        for (uint256 i = 0; i < g.commitCacheList.length; i++) {
Here we want to find `commitCache` with maximum nodes(maximal length of `commitCache.nodeIdAddress`) in `g.commitCacheList`. We take the first element as temporary expected value, and compare it with the rest elements. So `for (uint256 i = 0; i < g.commitCacheList.length; i++)` should be modified to `for (uint256 i = 1; i < g.commitCacheList.length; i++)`. And I'd like to know if there is a better way.

2023-01-27 03:31 UTC, kafeikui commented on contracts/src/Controller.sol
> +            for (uint256 j = 0; j < groupA.members.length; j++) {
why don't we use `getMemberAddressByIndex` here?

2023-01-27 03:40 UTC, kafeikui commented on contracts/src/Controller.sol
> +            groupBIndex = tempIndex;
(groupA, groupB) = (groupB, groupA);
(groupAIndex, groupBIndex) = (groupBIndex, groupAIndex);

2023-01-27 15:49 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        uint256[] memory remainingIndices = indices;
Completed!

2023-01-27 16:03 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +            for (uint256 j = 0; j < groupA.members.length; j++) {
completed!

2023-01-27 16:09 UTC, wrinkledeth commented on contracts/src/Controller.sol
>          }
good catch. Completed

2023-01-27 16:11 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        CommitCache memory majorityCommitCache = g.commitCacheList[1];
Okay I've corrected it, let me know if it looks okay.

2023-01-27 16:12 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +            groupBIndex = tempIndex;
nice! completed

2023-01-27 16:21 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        for (uint256 i = 0; i < g.commitCacheList.length; i++) {
Understood. Completed this change.

2023-01-27 16:25 UTC, wrinkledeth commented
@kafeikui , just commited another set of changes addressing your latest comments.

2023-01-27 17:08 UTC, kafeikui approved these changes
LGTM! Please merge the pr.

2023-01-30 18:50 UTC, merged

2023-01-30 18:50 UTC, wrinkledeth commented
Thanks! This has been merged.