Complete postproccessdkg
ARPA-Network/BLS-TSS-Network pull request #15
Opened 2023-02-07 04:57 UTC by wrinkledeth

Completed postProcessDkg(), slashNode(), freezeNode(), nodeStake(), and nodeUnstake() + relevant tests.

2023-02-15 05:38 UTC, kafeikui commented on contracts/src/Controller.sol
> +    event groupRelayTask(
We don't involve relay feature in the first version, so this can be removed.

2023-02-15 05:40 UTC, kafeikui commented on contracts/src/Controller.sol
> +        if (!isStrictlyMajorityConsensusReached) {
I can't see the reason to reverse the if condition, we need to keep the former logic. Since we don't have to do anything like emit relay event on isStrictlyMajorityConsensusReached, then the code should be like
```
if (!isStrictlyMajorityConsensusReached) {
    ...do arrange member things...
}
rewards[msg.sender] += DKG_POST_PROCESS_REWARD;
```

2023-02-15 05:45 UTC, kafeikui commented on contracts/src/Controller.sol
> +                g.threshold = g.threshold > minimum
not g.threshold
```
g.threshold = DEFAULT_MINIMUM_THRESHOLD > minimum
                    ? DEFAULT_MINIMUM_THRESHOLD
                    : minimum;
```

2023-02-15 05:48 UTC, kafeikui commented on contracts/src/Controller.sol
> +                    );
We need to [arrange group members when post_process_dkg even if disqualified_nodes is empty](https://github.com/ARPA-Network/BLS-TSS-Network/commit/e8b475b7f503020c5a85cd650440127cffa8d0a7), please refer to #14

2023-02-15 06:14 UTC, kafeikui commented on contracts/src/Controller.sol
> +                }
We need to handle the possible gaps in g.members by `delete g.members[i]` during or after the for loop. Element order in the array is not that important, so we can swap with the last and pop the last, like the for loop you wrote in line 499-509. Also, make sure the outer loop iterating `disqualifiedNodes` as it won't affect `delete` element in `g.members` during loop, and possibly save cycles.

2023-02-15 06:20 UTC, kafeikui commented on contracts/src/Controller.sol
> +        }
That's ok, and we also need an external `node_quit` function.

2023-02-15 06:22 UTC, kafeikui commented on contracts/src/Controller.sol
> +        // require(node.staking - unstakeAmount >= 0, "Cannot unstake more than amount staked"); //need this?
Not really, evm will revert if there is over/underflow on uint over solidity 0.8.

2023-02-15 06:42 UTC, kafeikui commented on contracts/src/Controller.sol
> +                    // try to reblance each group, if a any fail, set rebalanceFailure to true
The behavior should be described like "try to reblance each group, if succeed in rebalancing, break the loop and set rebalanceFailure to false". Almost like code at line108-112. Also, groupIndices[i] is right instead of i.
```
            bool rebalanceFailure = true;
            for (uint256 i = 0; i < groupIndices.length; i++) {
                if (rebalanceGroup(groupIndices[i], groupIndex)) {
                    rebalanceFailure = false;
                    break;
                }
            }
```

2023-02-15 06:53 UTC, kafeikui commented on contracts/src/Controller.sol
> +                            delete (_needsRebalance); //! Used to supress "unused parameter" warning, should I just leave this out?
We can destructure return value and ignore some value in solidity too. 

(uint256 targetGroupIndex, ) = findOrCreateTargetGroup();

2023-02-15 07:00 UTC, kafeikui commented on contracts/src/Controller.sol
> +                            // if group at targetGroupIndex now has 3+ members, emit group event
I think it's better to follow the rust mock version, as `emitGroupEvent` will prepare all the environment on that group as well as building coordinator and `emit dkgTask`, we don't want that happen on the same group repeatedly but only on the latest state.

2023-02-15 07:18 UTC, kafeikui requested changes
Besides comments on Controller.sol(src), we need to cover test case on `commitDkg/postProcessDkg` with different `CommitResult`(groupEpoch, publicKey and disqualifiedNodes), e.g. all identical, happy path(as we already have), there is no strict majority CommitResult, there is a strictly majority CommitResult but not exceeding threshold and finally, there is a strictly majority CommitResult and exceeding threshold but not all identical.

2023-02-21 03:21 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +    event groupRelayTask(
done

2023-02-21 03:21 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                g.threshold = g.threshold > minimum
done

2023-02-21 03:21 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        if (!isStrictlyMajorityConsensusReached) {
you're right, the condition should not have been reversed. This has been completed.

2023-02-21 03:34 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                            delete (_needsRebalance); //! Used to supress "unused parameter" warning, should I just leave this out?
Wow! Thank you for this.

2023-02-21 03:34 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +        // require(node.staking - unstakeAmount >= 0, "Cannot unstake more than amount staked"); //need this?
understood.

2023-02-21 03:36 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                        .isStrictlyMajorityConsensusReached = false;
To clarify, do you mean that:

```
                    groups[groupIndex]
                        .isStrictlyMajorityConsensusReached = false;
```
                        
Should be moved to 907?

2023-02-21 03:43 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                    // try to reblance each group, if a any fail, set rebalanceFailure to true
Makes sense, thank you!

2023-02-21 03:46 UTC, kafeikui commented on contracts/src/Controller.sol
> +                        .isStrictlyMajorityConsensusReached = false;
yes, then we will set `isStrictlyMajorityConsensusReached` of the current group to false no matter succeed in rebalancing.

2023-02-22 22:37 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                        .isStrictlyMajorityConsensusReached = false;
done

2023-02-22 23:00 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                }
To confirm this what you are looking for right?

```js
                for (uint256 j = 0; j < disqualifiedNodes.length; j++) {
                    for (uint256 i = 0; i < g.members.length; i++) {
                        if (g.members[i].nodeIdAddress == disqualifiedNodes[j]) {
                            g.members[i] = g.members[g.members.length - 1];
                            g.members.pop();
                            break;
                        }
                    }
                }
```

2023-02-22 23:14 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                    // if rebalance failed, start DKG for groupIndex
I think i noticed a potential bug here. 

When groupCount == 1:

groupIndices will be length 0, and so lines 901-903 will not run, and rebalanceFailure can never be set to true.

What should happen when there is only 1 group with 3 members. When we call freezeNode on a node, that node will get removed group the group, and we fall below 3 members ( the default minimum threshold). Which means we should set isStrictylMajorityConsensus reached to False, right?

Wondering if we should write an edgecase to handle when groupCount == 1?

2023-02-23 01:49 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                                break;
Should this be continue instead?

2023-02-23 03:45 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                            // if group at targetGroupIndex now has 3+ members, emit group event
Apologies, I see my mistake now. I have corrected it to match the rust mock contract.

2023-02-23 03:49 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                    );
Okay I see, so I should implement arrange_members_in_group() in solidity and include it at the end of post_proccess_dkg()?

2023-02-23 04:24 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                                break;
sorry, ignore this please.

2023-02-23 22:22 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                    // if rebalance failed, start DKG for groupIndex
This has been resolved, please ignore the above.

2023-02-23 22:46 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                    );
This has been completed!

2023-02-23 22:46 UTC, wrinkledeth commented on contracts/src/Controller.sol
> +                }
completed

2023-02-24 05:01 UTC, wrinkledeth commented
Latest commit addresses the issues raised above and includes the following changes: 
- bug fixes in postProccessDkg() and freezeNode()
- arrangeMembersInGroup() implemented. 
- nodeQuit() implemented (still need erc20 interaction). 
- Fixed bug in removeFromGroup() when group.size == 0
-  cleaned up comments / changed formatting to Forge instead of Prettier.

Upcoming work planned for next PR: 
- add erc20 interaction to nodeStake and nodeQuit,
- consolidate threshold logic to emitGroupEvent,
- writing proper tests for postproccessdkg / freezenode.

2023-02-25 16:33 UTC, kafeikui commented on contracts/src/Controller.sol
> +            }
We can use a bitmap to avoid removing duplicate. Since we are dealing it in memory, a bool[] should be ok.

2023-02-25 16:39 UTC, kafeikui commented on contracts/src/Controller.sol
> +            }
I think we can merge the pr first then improve it.

2023-02-25 16:41 UTC, kafeikui approved these changes

2023-02-26 09:00 UTC, merged